version: '3.8'

services:
  adminback:
    image: adminback
    build:
      context: ./simswap_backend      # Asegúrate de que el contexto y el Dockerfile están correctamente especificados
      dockerfile: Dockerfile
    volumes:
      - ./simswap_backend:/app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: simswap
      ECRET_KEY: "claveSecreta"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 180
      EMAIL_SENDER: "simswap45@gmail.com"
      EMAIL_PASSWORD: "zxcvb123."
      STRIPE_SECRET_KEY: 'sk_test_51PSNhmHM4dpKHzAOASgyRP1dX8wxL4qd7tjtOHIsOMdVDqVNEa2RoafmAQxUppioiZRgDjvmxhQw8klJE2XD7mpE00AoOdCPuq'
    networks:
      - basedatosusuarioss_backend-network
  


  adminfront:
    image: adminfront
    build: 
      context: ./simswap_test
      dockerfile: Dockerfile
    volumes:
      - ./cumarai-intelligent-business:/app
    environment:
      PORT: "3000"
      REACT_APP_GEOAPIFY_API_KEY: "7c4d3cacd6244d6b8da9038d618ea384"
      
    depends_on:
      - adminback
    networks:
      - basedatosusuarioss_backend-network

  

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - adminback
      - adminfront
    networks:
      - basedatosusuarioss_backend-network

networks:
  basedatosusuarioss_backend-network:
    external: true

volumes:
  mysql_data:
